### ISSUE TITLE
Multiple covariates

### ISSUE THREAD

**Issue by wchapman** [jrclimer/mle_rhythmicity#2]
To implement a VCO test, the documentation led me to attempt:

```
[params confidence stats everything] = rhythmicity_covar(root.cel_ts{1}, root.b_ts(end), ...
    [root.cel_vel{1}.*abs(cosd(root.cel_headdir{1})) abs(root.cel_vel{1}.*sind(root.cel_headdir{1}))],...
    'f_covar',[0 1 2], ... 
    'covar_labels',{'x_vel','y_vel'}, ...
    'post_hocs',struct('f',1));
```

Which throws an error when describing the design matrix (line 145). 

May be misreading the documentation, or bug in multiple covariates for a single parameter.

**Comment by jrclimer** [comment]
So, you'd probably want to add the speed to your design matrix, because the components are correlated with the speed alone we need to test to see if it's just the speed tuning of the rhythmicity. The post hoc tests currently only drop one column from the test, I need to implement a way for you to drop both of the components, but that will probably involve tweaking the way post_hocs is input.
